#Robocode Robot Properties
robot.description=Hadurling - the robot built in the Building Hadur course.
robot.author.name=course
robot.classname=hadurling.Hadurling
robot.version=0.1
robocode.version=1.9.5.6
